### PR TITLE
Gps with car

### PR DESCRIPTION
**Pull request by eyuell**
## Description
The GPS location would be sent to the app on request.
The angle of rotation for automatic movement is set between random values between 30 and 160 degrees.
## Related issue(s)
Issue numbers #43 and #16

### CODE REVIEW

**Review by AugustAxelsson — CHANGES_REQUESTED** [review]
Please remove the extra gps.ino files and add the method sendGPS() when a rfid tag is detected.
Otherwise it looks good!

**Review by MarcusAronsson1 — APPROVED** [review]

**Review by AugustAxelsson — APPROVED** [review]

**Comment by malties** [comment]
@platisd can you help us with travis? :)

**Comment by platisd** [comment]
@malties what is the problem you're facing?

**Comment by malties** [comment]
@platisd it was the stuff marcus commented to you about!

**Pull request merged**
