### PR TITLE
Gps with car

### PR DESCRIPTION
**Pull request by eyuell**
## Description
The conversion from decimal to degree and minutes is prepared.
Display Mine location when detected.
And minor angle correction for forward and backward movements.
## Related issue(s)
#74 #40 #5

### CODE REVIEW

**Comment by eyuell** [comment]
Lines updated are 385-387 and 401

**Comment by eyuell** [comment]
New Commit related to displaying location when mine is detected. And Forward and Backward movements corrected with offset angles.

**Review by MarcusAronsson1 — APPROVED** [review]
Nice that you removed magic numbers!

**Comment by MarcusAronsson1** [comment]
@eyuell 
If the issues are actually fixed with this pull request, put it like this "Fixes #number here" and github will automatically close the issues and move them to done. These issues are still open and we don't know if that's intended.

**Pull request merged**
