### PR TITLE
Create pull_request_template.md

### PR DESCRIPTION
**Pull request by eyuell**
template for pull requests

### CODE REVIEW

**Comment by MarcusAronsson1** [comment]
Have you seen that there already exists a pull request template in the master branch? It was added about 3 hours ago by Dimitris.
Is this one to replace the one already present?

**Comment by platisd** [comment]
Yeah, I merged that one without realizing @eyuell wanted to create his own. No problem with using this one, however, I do find specifying who should be review it in the pull request description a bit... unorthodox! :stuck_out_tongue:

**Comment by eyuell** [comment]
I think Dimtris just created the issue, I created the template. (Unless I miss something).

On the link below from of github, it states on step 4 to add mentions of team member to review. May be not applicable for this project.

https://help.github.com/en/articles/creating-a-pull-request-template-for-your-repository

**Comment by platisd** [comment]
@eyuell I created a pull request (#29), which you approved and then closed without merging which confused me! :laughing:
In regards to the mentions, I am not sure if that guide is outdated, but I guess you can add them to the body of the description. However, nowadays you can always request a review from them directly.

**Comment by eyuell** [comment]
Now I understand 'close' in here is canceling (not as 'Approval Done'). Thus, I am applying 'close' on this request. I am learning on many of the functionalities of git. Thanks.

**Pull request closed without merging**
