### PR TITLE
Added the gyroscope function to the smart car.

### PR DESCRIPTION
**Pull request by AugustAxelsson**
We also made some test with it. E.g we made a test designed so that the car will only move if the gyroscope heading is under 180 degrees. 

This fixes issue #20 for sprint 1

### CODE REVIEW

**Comment by platisd** [comment]
Please fix the pull request title and description. Additionally, you should ideally mention which this pull request fixes or is related to.

**Review by AdamKlevfors — APPROVED** [review]
This test looks good. How did you feel it worked in practise?

**Comment by AugustAxelsson** [comment]
> This test looks good. How did you feel it worked in practise?

It went well, thanks!

**Comment by AugustAxelsson** [comment]
> Please fix the pull request title and description. Additionally, you should ideally mention which this pull request fixes or is related to.

Thanks for your quick feedback, please have a look on it now.

**Pull request merged**
